const {test,expect}=require('@playwright/test');
const crypto=require('node:crypto');
const fs=require('node:fs');
const http=require('node:http');
const net=require('node:net');
const os=require('node:os');
const path=require('node:path');
const {spawn}=require('node:child_process');

const artifacts=process.env.PROVISIONARR_BROWSER_ARTIFACTS||path.join(os.tmpdir(),'provisionarr-browser-artifacts');
let root,child,baseURL;

function passwordRecord(password){const salt=crypto.randomBytes(16).toString('hex');return {salt,hash:crypto.scryptSync(password,salt,64).toString('hex')};}
async function port(){const server=net.createServer();await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',resolve).on('error',reject));const value=server.address().port;await new Promise(resolve=>server.close(resolve));return value;}
async function waitFor(url){for(let i=0;i<100;i++){try{if((await fetch(url)).ok)return;}catch{}await new Promise(resolve=>setTimeout(resolve,25));}throw new Error(`Fixture app did not start: ${url}`);}
function posterAsset(id,color='#315a73'){return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="320" height="480"><rect width="100%" height="100%" fill="${color}"/><circle cx="160" cy="170" r="86" fill="#ffffff22"/><text x="160" y="355" fill="white" font-family="sans-serif" font-size="24" text-anchor="middle">SYNTHETIC ${id}</text></svg>`)}`;}
function item(title,type,id,reason='Synthetic fixture recommendation',extra={}){return {kind:'media',mediaRef:`${type}-${id}`,title,year:2025,releaseDate:'2025-01-02T00:00:00Z',mediaType:type,service:type==='movie'?'radarr':'sonarr',identity:`${type}:${type==='movie'?'tmdb':'tvdb'}:${id}`,poster:posterAsset(id,extra.color||'#315a73'),overview:'Synthetic fixture-only browser data.',reason,fixture:true,availability:'can_request',actions:['view','propose_request'],...extra};}
function discover(type,mode='ready',tvGeneric=false){const movie=item('Synthetic Movie Fresh','movie',101);const movies=mode==='empty'?{status:'empty',message:'No new movies right now.',rails:{}}:mode==='unavailable'?{status:'unavailable',message:'Synthetic Radarr provider error.',rails:{}}:{status:'ready',rails:{inspired:type==='movie'?[movie]:[],trending:[],popular:[],newReleases:[]}};const generic=item('Synthetic Generic TV Fixture With A Deliberately Long Wrapped Title','series',201,'Generic TV catalog',{rating:8.4,color:'#72516e'});generic.identity='series:tvmaze:201';return {movies,tv:tvGeneric?{status:'ready',generic:true,attribution:'Generic TV catalog data from TVmaze, licensed CC BY-SA. Synthetic fixture content.',rails:{catalog:type==='series'?[generic]:[],inspired:[],trending:[],popular:[],newReleases:[]}}:{status:'unavailable',message:'TV discovery is unavailable in this synthetic fixture because no supported TV discovery provider is configured.',rails:{}}};}
function library(type,sort,page){const movieRows=[item('Synthetic Library Alpha With An Intentionally Long Two Line Movie Title','movie',301,'Synthetic owned fixture',{rating:8.6,color:'#496b47'}),item('Synthetic Library Beta','movie',302,'Synthetic owned fixture',{rating:7.2,color:'#6d4d47'}),item('Synthetic Library Unrated Long Form Film','movie',303,'Synthetic owned fixture',{rating:null,color:'#4e5c88'}),item('Synthetic Library Delta','movie',304,'Synthetic owned fixture',{rating:9.1,color:'#805d32'})],tvRows=[item('Synthetic Library TV Premiere With A Long Two Line Series Title','series',401,'Synthetic owned fixture',{rating:9.3,color:'#5b4f86'}),item('Synthetic Library TV Second Season','series',402,'Synthetic owned fixture',{rating:7.8,color:'#3c6e73'}),item('Synthetic Library TV Unrated','series',403,'Synthetic owned fixture',{rating:null,color:'#755148'})];const rows=type==='series'?tvRows:movieRows;const ordered=sort==='rating'?[...rows].sort((a,b)=>(b.rating??-Infinity)-(a.rating??-Infinity)):rows;const pageSize=2,pageRows=ordered.slice((page-1)*pageSize,page*pageSize);return {status:'ready',type,sort,page,pageSize,total:ordered.length,totalPages:Math.ceil(ordered.length/pageSize),hasMore:page<Math.ceil(ordered.length/pageSize),items:pageRows.map(row=>({...row,availability:'library_or_monitored'}))};}
async function screenshot(page,name){fs.mkdirSync(artifacts,{recursive:true});await page.screenshot({path:path.join(artifacts,name),fullPage:true});}
function contrastRatio(foreground,background){const rgb=value=>value.match(/\d+(?:\.\d+)?/g).slice(0,3).map(Number).map(channel=>{const normalized=channel/255;return normalized<=.04045?normalized/12.92:((normalized+.055)/1.055)**2.4;});const luminance=value=>{const [r,g,b]=rgb(value);return .2126*r+.7152*g+.0722*b;};const [light,dark]=[luminance(foreground),luminance(background)].sort((a,b)=>b-a);return (light+.05)/(dark+.05);}

test.beforeAll(async()=>{
  root=fs.mkdtempSync(path.join(os.tmpdir(),'provisionarr-browser-fixture-'));
  const password='browser-fixture-password';
  fs.writeFileSync(path.join(root,'users.json'),JSON.stringify([{id:'user',username:'user',displayName:'Fixture User',role:'user',...passwordRecord(password),preferences:{}}]));
  const appPort=await port();baseURL=`http://127.0.0.1:${appPort}`;
  child=spawn(process.execPath,[path.join(__dirname,'..','server.js')],{env:{...process.env,PORT:String(appPort),PROVISIONARR_LISTEN_HOST:'127.0.0.1',PROVISIONARR_CONFIG_ROOT:root,PROVISIONARR_USERS_FILE:path.join(root,'users.json'),PROVISIONARR_SETTINGS_FILE:path.join(root,'settings.json'),PROVISIONARR_REQUEST_LOG:path.join(root,'requests.json'),PROVISIONARR_ADMIN_FILE:path.join(root,'admin.json'),PROVISIONARR_AUDIT_FILE:path.join(root,'audit.jsonl'),PROVISIONARR_SESSION_FILE:path.join(root,'sessions.json'),SONARR_URL:'http://127.0.0.1:65534',RADARR_URL:'http://127.0.0.1:65534',PROVISIONARR_EMBY_URL:'',PROVISIONARR_EMBY_API_KEY:''},stdio:'ignore'});
  await waitFor(`${baseURL}/api/bootstrap`);
});
test.afterAll(async()=>{if(child?.exitCode===null)child.kill();if(child?.exitCode===null)await new Promise(resolve=>child.once('exit',resolve));if(root)fs.rmSync(root,{recursive:true,force:true});});

async function login(page){await page.goto(`${baseURL}/#/account`);await page.getByLabel('Username').fill('user');await page.getByLabel('Password').fill('browser-fixture-password');await page.locator('#login-form').getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/#\/home$/);}
function fixtureRoutes(page,state){page.on('pageerror',error=>state.errors.push(`pageerror: ${error.message}`));page.on('console',message=>{if(message.type()==='error')state.errors.push(`console: ${message.text()}`);});return page.route('**/api/{discover,search,library}*',async route=>{const request=new URL(route.request().url());if(request.pathname==='/api/discover'){if(state.delay)await new Promise(resolve=>setTimeout(resolve,state.delay));if(state.error)return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Fixture discovery failed.'})});return route.fulfill({contentType:'application/json',body:JSON.stringify(discover(request.searchParams.get('type')||'movie',state.empty?'empty':'ready',state.tvGeneric===true))});}if(request.pathname==='/api/search'){const type=request.searchParams.get('type')||'movie',page=Number(request.searchParams.get('page')||1),rows=type==='series'?[item(page===2?'Fixture TV Search Next':'Fixture TV Search','series',500+page)]:[item(page===2?'Fixture Movie Search Next':'Fixture Movie Search','movie',600+page)];return route.fulfill({contentType:'application/json',body:JSON.stringify({results:rows,page,totalPages:2,hasMore:page<2})});}const type=request.searchParams.get('type')||'movie',sort=request.searchParams.get('sort')||'title',page=Number(request.searchParams.get('page')||1);return route.fulfill({contentType:'application/json',body:JSON.stringify(library(type,sort,page))});});}

test('fixture catalog desktop navigation covers discovery, search, Library, sorting, paging, Back, and refresh',async({page})=>{
  const state={errors:[],tvGeneric:true};await fixtureRoutes(page,state);await page.setViewportSize({width:1440,height:1000});await login(page);
  await expect(page.locator('#catalog-context')).toHaveValue('movie');await expect(page.getByRole('button',{name:'View Synthetic Movie Fresh'})).toBeVisible();await expect(page.getByText('Owned Movie',{exact:true})).toHaveCount(0);await screenshot(page,'desktop-discovery-movies.png');
  await page.locator('#catalog-context').selectOption('series');await expect(page).toHaveURL(/#\/home\?type=series$/);await expect(page.getByText(/Generic TV catalog data from TVmaze.*Synthetic fixture content/)).toBeVisible();await expect(page.getByText('Synthetic Generic TV Fixture With A Deliberately Long Wrapped Title')).toBeVisible();await expect(page.getByText('Trending now')).toHaveCount(0);await expect(page.getByText('Synthetic Movie Fresh',{exact:true})).toHaveCount(0);await screenshot(page,'desktop-generic-tv-unowned-fixture.png');
  await page.goBack();await expect(page).toHaveURL(/#\/home$/);await expect(page.getByRole('button',{name:'View Synthetic Movie Fresh'})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'View Synthetic Movie Fresh'})).toBeVisible();
  await page.goto(`${baseURL}/#/search?query=fixture&type=movie`);await expect(page.locator('#catalog-context')).toHaveValue('movie');await expect(page.getByRole('button',{name:'View Fixture Movie Search'})).toBeVisible();await page.locator('#catalog-context').selectOption('series');await expect(page).toHaveURL(/type=series/);await expect(page.getByRole('button',{name:'View Fixture TV Search'})).toBeVisible();await page.getByRole('link',{name:'Next'}).click();await expect(page.getByRole('button',{name:'View Fixture TV Search Next'})).toBeVisible();await page.goBack();await expect(page.getByRole('button',{name:'View Fixture TV Search'})).toBeVisible();
  await page.goto(`${baseURL}/#/library?type=movie&sort=title`);await expect(page.getByRole('button',{name:'View Synthetic Library Alpha With An Intentionally Long Two Line Movie Title'})).toBeVisible();await page.locator('#catalog-sort').selectOption('rating');await expect(page).toHaveURL(/sort=rating/);await expect(page.getByRole('button',{name:'View Synthetic Library Delta'})).toBeVisible();await expect(page.getByText('Rating 9.1')).toBeVisible();await page.getByRole('link',{name:'Next'}).click();await expect(page).toHaveURL(/page=2/);const unrated=page.getByRole('button',{name:'View Synthetic Library Unrated Long Form Film'});await expect(unrated).toBeVisible();await expect(unrated.locator('p')).not.toContainText('Rating');await screenshot(page,'desktop-library-pagination.png');
  expect(state.errors).toEqual([]);
});

test('fixture catalog reports loading, typed empty, and error states',async({page})=>{
  const state={errors:[],delay:400};await fixtureRoutes(page,state);await login(page);await expect(page.getByText('Loading recommendations…')).toBeVisible();await expect(page.getByRole('button',{name:'View Synthetic Movie Fresh'})).toBeVisible();state.delay=0;state.empty=true;
  await page.goto(`${baseURL}/#/home?type=movie`);await screenshot(page,'desktop-discovery-empty.png');await expect(page.locator('.catalog-state strong')).toHaveText('No new movies right now.');await page.goto(`${baseURL}/#/home?type=series`);await expect(page.getByText('TV shows recommendations are unavailable.')).toBeVisible();state.empty=false;state.error=true;
  await page.goto(`${baseURL}/#/home?type=movie`);await expect(page.getByText('Fixture discovery failed.')).toBeVisible();await screenshot(page,'desktop-discovery-error.png');expect(state.errors).toEqual(['console: Failed to load resource: the server responded with a status of 503 (Service Unavailable)']);
});

test('fixture catalog narrow layout keeps Library type context through sorting, paging, Back, and refresh',async({page})=>{
  const state={errors:[]};await fixtureRoutes(page,state);await page.setViewportSize({width:390,height:844});await login(page);await expect(page.locator('#catalog-context')).toBeVisible();const box=await page.locator('#catalog-context').boundingBox();expect(box.height).toBeGreaterThanOrEqual(44);await page.locator('#catalog-context').selectOption('series');await expect(page).toHaveURL(/#\/home\?type=series$/);await expect(page.getByText('TV shows recommendations are unavailable.')).toBeVisible();await expect(page.getByText(/synthetic fixture/i)).toBeVisible();await screenshot(page,'mobile-tv-discovery-390x844-fixture.png');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
  await page.locator('#catalog-context').selectOption('library');await expect(page).toHaveURL(/#\/library\?type=series/);await expect(page.locator('#catalog-context')).toHaveValue('series');await expect(page.locator('#catalog-sort')).toBeVisible();await page.locator('#catalog-sort').selectOption('rating');await expect(page).toHaveURL(/type=series&sort=rating/);const tvCard=page.getByRole('button',{name:'View Synthetic Library TV Premiere With A Long Two Line Series Title'});await expect(tvCard).toBeVisible();await expect(page.getByText('Rating 9.3')).toBeVisible();await expect(page.getByText('Synthetic fixture').first()).toBeVisible();await screenshot(page,'mobile-library-tv-rating-pagination-390x844-synthetic.png');const menu=page.locator('#mobile-menu');await expect(menu).toHaveText(/Menu · Library/);expect((await menu.boundingBox()).height).toBeGreaterThanOrEqual(44);const [titleBox,metaBox,cardBox,titleStyle,metaStyle]=await Promise.all([tvCard.locator('h3').boundingBox(),tvCard.locator('p').boundingBox(),tvCard.boundingBox(),tvCard.locator('h3').evaluate(node=>getComputedStyle(node).color+'|'+getComputedStyle(node).fontSize+'|'+getComputedStyle(node).webkitLineClamp),tvCard.locator('p').evaluate(node=>getComputedStyle(node).color+'|'+getComputedStyle(node).fontSize)]);expect(titleBox.y+titleBox.height).toBeLessThanOrEqual(metaBox.y+1);expect(metaBox.y+metaBox.height).toBeLessThan(cardBox.y+cardBox.height-4);const [titleColor,titleSize,titleLines]=titleStyle.split('|'),[metaColor,metaSize]=metaStyle.split('|');expect(Number.parseFloat(titleSize)).toBeGreaterThanOrEqual(15);expect(Number.parseFloat(metaSize)).toBeGreaterThanOrEqual(12);expect(titleLines).toBe('2');expect(contrastRatio(titleColor,'rgb(7, 16, 23)')).toBeGreaterThanOrEqual(4.5);expect(contrastRatio(metaColor,'rgb(7, 16, 23)')).toBeGreaterThanOrEqual(4.5);await expect(page.getByText('Synthetic Generic TV Fixture With A Deliberately Long Wrapped Title')).toHaveCount(0);await expect(page.getByText('In library').first()).toBeVisible();
  await page.locator('#catalog-context').selectOption('movie');await expect(page).toHaveURL(/#\/library\?type=movie/);await expect(page.locator('#catalog-context')).toHaveValue('movie');await expect(page.getByRole('button',{name:'View Synthetic Library Delta'})).toBeVisible();await expect(page.getByText('Synthetic Movie Fresh',{exact:true})).toHaveCount(0);await page.locator('#catalog-sort').selectOption('rating');await expect(page).toHaveURL(/type=movie&sort=rating/);await expect(page.getByRole('link',{name:'Next'})).toBeVisible();await screenshot(page,'mobile-library-type-sort-pagination-390x844-fixture.png');expect((await page.locator('#catalog-sort').boundingBox()).height).toBeGreaterThanOrEqual(44);await page.getByRole('link',{name:'Next'}).click();await expect(page).toHaveURL(/type=movie&sort=rating&page=2/);await expect(page.getByRole('button',{name:'View Synthetic Library Unrated Long Form Film'})).toBeVisible();await page.goBack();await expect(page.locator('#catalog-context')).toHaveValue('movie');await expect(page.locator('#catalog-sort')).toHaveValue('rating');await page.reload();await expect(page.locator('#catalog-context')).toHaveValue('movie');await expect(page.locator('#catalog-sort')).toHaveValue('rating');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);expect(state.errors).toEqual([]);
});
